### PR TITLE
Fix #323 If users try to upload a resource named venv.zip#archive, To…

### LINKED ISSUE #323: If users try to upload a resource named venv.zip#archive, TonY job would fail
```19/06/10 20:26:39 INFO tony.TaskExecutor: Unpacking Python virtual environment..

19/06/10 20:26:39 INFO util.Utils: Unzipping venv.zip to destination venv

19/06/10 20:26:39 FATAL util.Utils: Failed to unzip venv.zip

net.lingala.zip4j.exception.ZipException: java.io.FileNotFoundException: venv.zip (Is a directory)

        at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:431)

        at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:475)

        at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:451)

        at com.linkedin.tony.util.Utils.unzipArchive(Utils.java:168)

        at com.linkedin.tony.TaskExecutor.extractResources(TaskExecutor.java:207)

        at com.linkedin.tony.TaskExecutor.main(TaskExecutor.java:102)```

### PR DESCRIPTION
**Pull request by oliverhu**
…nY job would fail

### CODE REVIEW

File: tony-core/src/main/java/com/linkedin/tony/TaskExecutor.java [hunk 1]
```diff
@@ -202,7 +202,7 @@ private static void extractResources() {
       LOG.info("Unpacking src directory..");
       Utils.unzipArchive(Constants.TONY_SRC_ZIP_NAME, "./");
     }
-    if (new File(Constants.PYTHON_VENV_ZIP).exists()) {
+    if (new File(Constants.PYTHON_VENV_ZIP).exists() && new File(Constants.PYTHON_VENV_ZIP).isFile()) {
```
Comment (erwa) [inline tony-core/src/main/java/com/linkedin/tony/TaskExecutor.java]: Can we factor `extractResources()` out into a utility class and have TaskExecutor and ApplicationMaster call it rather than duplicating code?

Comment (erwa) [reply tony-core/src/main/java/com/linkedin/tony/TaskExecutor.java]: Create a local variable to store `new File(Constants.PYTHON_VENV_ZIP)` rather than duplicating it.

Comment (oliverhu) [reply tony-core/src/main/java/com/linkedin/tony/TaskExecutor.java]: makes sense, updated

**Comment by erwa** [comment]
Checkstyle failed in CI.
